### ISSUE TITLE
ProvidedTypes.fs needs update for Mono 5.0

### ISSUE THREAD

**Issue by dsyme** [jet/JsonSchemaProvider#1]
If this project is still alive, please update to use the latest version of ProvidedTypes.fs, as instructed here:

 https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/121

**Comment by dsevastianov** [comment]
Not actively supported, but fix applied anyway.

**Comment by dsyme** [comment]
@dsevastianov Yep, I figured.  If you have time could you write up a quick summary of your lessons from the type provider? e.g
* Is the functionality useful enough to warrant a type provider?
* does it overlap with other type providers?
* is the implementation ok?
* would you want to take it forward if you found a collaborator, or is it best to archive it etc.)?

thx
don

**Comment by dsevastianov** [comment]
Fair, I'll need some time to consider. Will it be ok to have this posted on Jet's tech blog? I can definitely do both here and there, this one evidently didn't pick up too much attention.

**Comment by dsyme** [comment]
> Will it be ok to have this posted on Jet's tech blog? 

Of course. What ever you like, totally as you wish :)

**Comment by dsevastianov** [comment]
@dsyme Here it is, sorry it took so long: 
https://github.com/jet/JsonSchemaProvider/blob/master/Postmortem.md
